import { Command } from "commander";
import chalk from "chalk";
import fs from "fs-extra";
import path from "node:path";
import { findRepoRoot } from "../lib/repoRoot.js";

const DEFAULT_DIRS = [
  "businessops/state",
  "businessops/docs/en",
  "businessops/docs/pt-br",
  "businessops/templates/docs/en",
  "businessops/templates/docs/pt-br",
  "businessops/commands",
  "businessops/workflows",
  "businessops/packs/industry-neutral",
  "businessops/packs/health-import",
  "businessops/reports",
  "businessops/diagrams"
];

const DEFAULT_FILES: Array<{ rel: string; content: string }> = [
  {
    rel: "businessops/state/schema-version.yaml",
    content: "schema_version: 0.1\n"
  },
  {
    rel: "businessops/state/answers.yaml",
    content: `wizard:
  workflow_id: businessops_wizard
  version: 0.1
  mode: robust

answers: {}
`
  },
  {
    rel: "businessops/state/company.yaml",
    content: `company:
  lifecycle_mode: NEW

  identity:
    name: ""
    country: "Brazil"
    one_liner: ""
    stage: EARLY
    headcount_range: SMALL
    company_age: ""

  market:
    customer_type: ["B2B"]
    icp: ""
    customer_pains: ""
    positioning: ""
    acquisition_channels: ["OUTBOUND_SALES"]

  revenue:
    model: TRANSACTIONAL

  pricing:
    model: NEGOTIATED
    discounting: UNKNOWN

  ops:
    delivery_type: INVENTORY
    complexity: MEDIUM
    outsourcing_level: SOME
    bottleneck: ""
    outsourced_services: ["ACCOUNTING"]

  processes:
    order_to_cash_steps: ["LEAD", "QUOTE", "ORDER", "INVOICE", "DELIVERY", "COLLECTION", "SUPPORT"]

  finance:
    payment_terms: ""
    revenue_range: ""
    gross_margin_range: ""

  reporting:
    kpis_tracked_today: ""

  compliance:
    regulated: UNKNOWN

  risks:
    top: ""

  goals:
    days_90: ""
    days_180: ""
    days_365: ""

meta:
  country_mode: BR
  language_preference: BILINGUAL
  packs: ["industry-neutral"]
`
  },
  {
    rel: "businessops/templates/docs/en/overview.md",
    content: `# Overview

<!-- BO:BEGIN GENERATED -->
This file will be generated by the CLI.
<!-- BO:END GENERATED -->
`
  },
  {
    rel: "businessops/templates/docs/pt-br/overview.md",
    content: `# Visão Geral

<!-- BO:BEGIN GENERATED -->
Este arquivo será gerado pelo CLI.
<!-- BO:END GENERATED -->
`
  }
];

async function writeIfMissing(abs: string, content: string, force: boolean) {
  const exists = await fs.pathExists(abs);
  if (!exists || force) {
    await fs.ensureDir(path.dirname(abs));
    await fs.writeFile(abs, content, "utf8");
    return true;
  }
  return false;
}

export const initCommand = new Command("init")
  .description("Initialize BusinessOps Toolkit structure + state files")
  .option("--force", "Overwrite existing files", false)
  .action(async (opts) => {
    const root = findRepoRoot();
    console.log(chalk.cyan("Initializing BusinessOps Toolkit in:"), chalk.gray(root));

    for (const dir of DEFAULT_DIRS) {
      await fs.ensureDir(path.join(root, dir));
    }

    for (const f of DEFAULT_FILES) {
      const abs = path.join(root, f.rel);
      const wrote = await writeIfMissing(abs, f.content, opts.force);
      if (wrote) console.log(chalk.green("Created:"), f.rel);
    }

    console.log(chalk.green("\nDone ✅"));
    console.log(chalk.cyan("\nNext:"));
    console.log(chalk.yellow("  npm run dev --prefix cli -- generate"));
  });
